# Generated by Django 3.2.10 on 2023-04-28 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230428_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.places', verbose_name='Место'),
        ),
    ]
